# Generated by Django 4.2.1 on 2023-05-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brname', models.CharField(max_length=50)),
                ('cutoff', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clgname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeatMetrixDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.branchdb')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.collegedb')),
            ],
        ),
    ]
