# Generated by Django 4.2.1 on 2023-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatmetrixdb',
            old_name='info',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='branchdb',
            name='cutoff',
        ),
        migrations.AddField(
            model_name='seatmetrixdb',
            name='cutoff',
            field=models.IntegerField(default=0),
        ),
    ]
