# Generated by Django 4.2.1 on 2023-05-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_info_seatmetrixdb_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatmetrixdb',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='seatmetrixdb',
            name='cutoff',
        ),
        migrations.AddField(
            model_name='seatmetrixdb',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
