# Generated by Django 4.2.1 on 2023-05-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_seatmetrixdb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmetrixdb',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
