# Generated by Django 4.2.1 on 2023-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_seatmetrixdb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatmetrixdb',
            name='info',
        ),
        migrations.AddField(
            model_name='seatmetrixdb',
            name='cutoff',
            field=models.IntegerField(default=-1),
        ),
    ]
