# Generated by Django 4.2.1 on 2023-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_seatmetrixdb_info_seatmetrixdb_cutoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatmetrixdb',
            name='cutoff',
        ),
        migrations.RemoveField(
            model_name='seatmetrixdb',
            name='name',
        ),
        migrations.AddField(
            model_name='seatmetrixdb',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
